name: Process Queue CI

on:
  push:
    branches: [master]
    paths: ['scripts/process-queue/**']
  pull_request:
    paths: ['scripts/process-queue/**']

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./scripts/process-queue
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version-file: './scripts/process-queue/.nvmrc'
          registry-url: 'https://npm.pkg.github.com'
      - name: Install
        # Skip post-install to avoid malicious scripts stealing PAT
        run: npm ci --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.REEDSY_BOT_PERSONAL_ACCESS_TOKEN }}
      - name: Post-install
        run: npm rebuild && npm run prepare --if-present
      - run: npm run lint
      - run: npm run typecheck
      - run: npm test -- --coverage
