name: Publish

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        registry-url: 'https://npm.pkg.github.com'
    - name: Build reencode action
      run: cd ./.github/actions/reencode-dictionaries && npm install && cd ../../../
    - name: Move dictoinaries to root folder
      run: cp ./ca/dictionaries/* ./ca
    - name: "Change dictionaries encoding to UTF-8"
      uses: ./.github/actions/reencode-dictionaries
    - name: Publish
      run: ./release.sh
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
